### ISSUE TITLE
'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

### ISSUE THREAD

**Issue by mdAdnn** [Illumina/Cyrius#28]
Hi,

Im getting this error despite everything properly, such as WGS bam file.

python3 star_caller.py --manifest /media/sf_Shared/Cyrius-master/caller/tests/test_data/NA23275.bam --genome 37 --prefix cyr --outDir test_output

Traceback (most recent call last):

  File "/media/sf_Shared/Cyrius-master/star_caller.py", line 562, in <module>

    main()

  File "/media/sf_Shared/Cyrius-master/star_caller.py", line 513, in main

    for line in read_manifest:

  File "/home/adnan/anaconda3/lib/python3.9/codecs.py", line 322, in decode

    (result, consumed) = self._buffer_decode(data, self.errors, final)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by xiao-chen-xc** [comment]
Hi @mdAdnn

The manifest should be a text file where each line gives the path to a bam file.
Additionally, the test data included with the program is for unit testing. You will need a WGS bam file as input to the program.

Thanks,
Xiao

**Comment by xiao-chen-xc** [comment]
What's in your Path.txt? Does it contain the absolute path to your NA12878_hg19.bam?

**Comment by mdAdnn** [comment]
yes 

'/media/sf_Shared/Cyrius-master/NA12878_hg19.bam'

'/media/sf_Shared/Cyrius-master/NA12878_hg19.bam.bai'

now its showing the following error when I reistalled the file:
python star_caller.py --manifest '/media/sf_Shared/Cyrius-master/caller/tests/test_data/Path.txt'  --genome 19 --prefix cyr --outDir test_output

WARNING:root:Input file for sample NA12878_hg19 does not exist.

WARNING:root:Input file for sample NA12878_hg19.bam does not exist.

INFO:root:Writing to json at 2022-09-29 13:04:01.454385

INFO:root:Writing to tsv at 2022-09-29 13:04:01.455826

**Comment by xiao-chen-xc** [comment]
Could you remove the quotes and retry? Also, no need to have a line for the .bai file.

**Comment by mdAdnn** [comment]
hi I got output file from someone else but when I'm runing the lmpgx code its showing the following error
python3 src/pgx.py -b BAM/CRAM -s NA18632 -o '/media/sf_Shared/PGx-master' -c lib/config.yml

Traceback (most recent call last):

  File "/home/adnan/PGx-master/src/pgx.py", line 9, in <module>

    from discover_variants import _annotate_genotypes

  File "/home/adnan/PGx-master/src/discover_variants.py", line 1, in <module>

    import vcf

  File "/home/adnan/anaconda3/lib/python3.9/site-packages/vcf/__init__.py", line 166, in <module>

    from parser import Reader, Writer

ImportError: cannot import name 'Reader' from 'parser' (/home/adnan/anaconda3/lib/python3.9/lib-dynload/parser.cpython-39-x86_64-linux-gnu.so)

**Comment by xiao-chen-xc** [comment]
Hi @mdAdnn this does not seem to be related to Cyrius. Please send this question to lmpgx authors. Thanks.

**Comment by mdAdnn** [comment]
Hi,
what are the genes cyrius deals with? Like is it specifically for CYP2D6 and CYP2D7 or some other genes as well?

**Comment by xiao-chen-xc** [comment]
Cyrius is a caller for CYP2D6.
