### ISSUE TITLE
How to correct "ZeroDivisionError: division by zero" ?

### ISSUE THREAD

**Issue by PavitaKae** [Illumina/Cyrius#35]
I run command star_caller.py, and i got this error 
```
INFO:root:Processing sample test at 2023-05-01 11:57:07.119751
Traceback (most recent call last):
  File "/path/Cyrius/Cyrius-v1.1.1/star_caller.py", line 562, in <module>
    main()
  File "/path/Cyrius/Cyrius-v1.1.1/star_caller.py", line 530, in main
    bam_name, call_parameters, threads, count_file, reference_fasta, index_name=index_name
  File "/path/Cyrius/Cyrius-v1.1.1/star_caller.py", line 312, in d6_star_caller
    raw_cn_call.d67_cn,
  File "/path/Cyrius/Cyrius-v1.1.1/caller/call_variants.py", line 269, in call_exon9gc
    d6_values.append(full_length_cn * count1 / (count1 + count2))
ZeroDivisionError: division by zero
```
How to correct this? it mean my sample test isn't have this region? 

Pavita

**Comment by xiao-chen-xc** [comment]
Hi Pavita, there is not enough coverage around the exon9 region. Is this a WGS sample with standard (>30X) coverage?

**Comment by PavitaKae** [comment]
thank you for your answer, i think coverage is cause of error.
